In [1]:
import genvarloader as gvl
import pooch
from pathlib import Path
import numpy as np
import src.vep_pipeline as vp
import src.clinvar as cv
import os,sys
print(sys.executable)
os.environ['PATH'] = '/grid/kinney/home/zhliu/.conda/envs/gvl_splicing/bin:' + os.environ['PATH']
!which python

/grid/kinney/home/zhliu/.conda/envs/gvl_splicing/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

/grid/kinney/home/zhliu/.conda/envs/gvl_splicing/bin/python
~/.conda/envs/gvl_splicing/bin/python

In [2]:
os.getcwd()

'/grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing'

In [3]:
# Download the correct 1KGP reference genome and haplotype variants
import os
import pooch
from src import config
from src.onekg import get_ftp_dict, list_remote_vcf, download_vcfs

# Set download directory
config.DATA_DIR = "/grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data"

# Set 1000 Genomes key
key = "1000_Genomes_on_GRCh38"

# 1. Download the reference genome
reference_url = get_ftp_dict()[key]["ref"]
reference_path = pooch.retrieve(url=reference_url, known_hash=None)
print(f"Reference genome saved at: {reference_path}")

# Compress ref genome if not already
if not Path(f"{reference_path}.bgz").exists():
    !bgzip -c {reference_path} > {reference_path}.bgz

# 2. List all available VCFs
manifest = list_remote_vcf(key=key)

# 3. Download all VCFs (including .vcf.gz and .tbi index files)
vcf_files = download_vcfs(key=key, manifest=manifest, skip_checks=True, verbose=True)
print(f"Downloaded {len(vcf_files)} files")

# 4. Print resulting files
vcf_paths = {k: v for k, v in vcf_files.items() if not k.endswith("_idx")}
index_paths = {k: v for k, v in vcf_files.items() if k.endswith("_idx")}

print("VCF paths:")
for k, v in vcf_paths.items():
    print(f"{k}: {v}")

print("Index file paths:")
for k, v in index_paths.items():
    print(f"{k}: {v}")

Reference genome saved at: /grid/kinney/home/zhliu/.cache/pooch/296ca04ba1df562072adc4c76f64cfb9-GRCh38_full_analysis_set_plus_decoy_hla.fa

Downloading VCF files: 100%|██████████████████████████████████████████████████| 46/46 [00:00<00:00, 4040.16it/s]

Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr1.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr1.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr2.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr2.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr3.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr3.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr4.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr4.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr5.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr5.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr6.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr6.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr7.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr7.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr8.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr8.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr9.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr9.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr10.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr10.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr11.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr11.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr12.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr12.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr13.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr13.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr14.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr14.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr15.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr15.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr16.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr16.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr17.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr17.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr18.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr18.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr19.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr19.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr20.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr20.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr21.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr21.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr22.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr22.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chrX.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz because it already exists
Skipping /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chrX.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi because it already exists
Downloaded 46 files
VCF paths:
chr1_vcf: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr1.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz
chr2_vcf: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr2.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz
chr3_vcf: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr3.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz
chr4_vcf: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr4.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz
chr5_vcf: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr5.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz
chr6_vcf: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr6.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz
chr7_vcf: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr7.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz
chr8_vcf: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr8.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz
chr9_vcf: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr9.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz
chr10_vcf: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr10.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz
chr11_vcf: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr11.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz
chr12_vcf: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr12.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz
chr13_vcf: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr13.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz
chr14_vcf: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr14.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz
chr15_vcf: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr15.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz
chr16_vcf: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr16.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz
chr17_vcf: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr17.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz
chr18_vcf: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr18.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz
chr19_vcf: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr19.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz
chr20_vcf: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr20.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz
chr21_vcf: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr21.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz
chr22_vcf: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr22.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz
chrX_vcf: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chrX.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz
Index file paths:
chr1_idx: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr1.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi
chr2_idx: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr2.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi
chr3_idx: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr3.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi
chr4_idx: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr4.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi
chr5_idx: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr5.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi
chr6_idx: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr6.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi
chr7_idx: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr7.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi
chr8_idx: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr8.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi
chr9_idx: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr9.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi
chr10_idx: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr10.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi
chr11_idx: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr11.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi
chr12_idx: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr12.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi
chr13_idx: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr13.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi
chr14_idx: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr14.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi
chr15_idx: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr15.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi
chr16_idx: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr16.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi
chr17_idx: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr17.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi
chr18_idx: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr18.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi
chr19_idx: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr19.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi
chr20_idx: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr20.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi
chr21_idx: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr21.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi
chr22_idx: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr22.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi
chrX_idx: /grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chrX.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz.tbi

In [7]:
# Rename, atomize, and index 1KGP haplotype variants for each chromosome
import subprocess
import pysam
from pathlib import Path

# Assume: vcf_paths is already defined and reference_bgz is the bgzipped reference FASTA
reference_bgz = Path(f"{reference_path}.bgz")
# Prepare rename file (if not already exists)
chr_rename_file = Path(config.DATA_DIR) / "1000_Genomes_on_GRCh38/chr_rename.txt"
if not chr_rename_file.exists():
    with open(chr_rename_file, "w") as f:
        for i in range(1, 23):
            f.write(f"{i}\tchr{i}\n")
        f.write("X\tchrX\nY\tchrY\nMT\tchrM\n")

for key, vcf_path in vcf_paths.items():
    chromosome = key.replace('_vcf', '')  # e.g., chr1
    vcf_path = Path(vcf_path)

    renamed_vcf = vcf_path.with_name(vcf_path.stem + ".renamed.vcf.gz")
    atomized_vcf = vcf_path.with_name(vcf_path.stem + ".atomized.vcf.gz")

    # Step 1: Rename chromosomes using bcftools view
    if not renamed_vcf.exists():
        print(f"Renaming chromosomes for: {vcf_path.name}")
        subprocess.run([
            "bcftools", "annotate",
            "--rename-chrs", str(chr_rename_file),
            "-Oz", "-o", str(renamed_vcf),
            str(vcf_path)
        ], check=True)
        
    # Step 2: Index renamed VCF
    if not Path(f"{renamed_vcf}.tbi").exists():
        print(f"Indexing renamed VCF: {renamed_vcf.name}")
        subprocess.run(["tabix", "-p", "vcf", str(renamed_vcf)], check=True)

    # Step 3: Atomize (normalize multi-allelics)
    if not atomized_vcf.exists():
        print(f"Atomizing: {renamed_vcf.name}")
        subprocess.run([
            "bcftools", "norm",
            "--threads", "16",  # <-- Adjust thread count as needed
            "-a", "-c", "s", "-m-any",
            "-f", reference_bgz,
            "-o", str(atomized_vcf),
            str(renamed_vcf)
        ], check=True)

    # Step 4: Index atomized VCF
    if not Path(f"{atomized_vcf}.tbi").exists():
        print(f"Indexing atomized VCF: {atomized_vcf.name}")
        subprocess.run(["tabix", "-p", "vcf", str(atomized_vcf)], check=True)

    # Optional: Verify with pysam
    vcf_in = pysam.VariantFile(str(atomized_vcf), "r")
    chroms = list(vcf_in.header.contigs)
    first_rec = next(vcf_in.fetch())
    print(f"✅ Chromosome renamed: {atomized_vcf.name} → Contigs: {chroms[:1]}, First record CHROM: {first_rec.chrom}")
    vcf_in.close()

✅ Chromosome renamed: ALL.chr1.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.atomized.vcf.gz → Contigs: ['chr1'], First record CHROM: chr1
✅ Chromosome renamed: ALL.chr2.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.atomized.vcf.gz → Contigs: ['chr2'], First record CHROM: chr2
✅ Chromosome renamed: ALL.chr3.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.atomized.vcf.gz → Contigs: ['chr3'], First record CHROM: chr3
✅ Chromosome renamed: ALL.chr4.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.atomized.vcf.gz → Contigs: ['chr4'], First record CHROM: chr4
✅ Chromosome renamed: ALL.chr5.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.atomized.vcf.gz → Contigs: ['chr5'], First record CHROM: chr5
✅ Chromosome renamed: ALL.chr6.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.atomized.vcf.gz → Contigs: ['chr6'], First record CHROM: chr6
✅ Chromosome renamed: ALL.chr7.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.atomized.vcf.gz → Contigs: ['chr7'], First record CHROM: chr7
✅ Chromosome renamed: ALL.chr8.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.atomized.vcf.gz → Contigs: ['chr8'], First record CHROM: chr8
✅ Chromosome renamed: ALL.chr9.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.atomized.vcf.gz → Contigs: ['chr9'], First record CHROM: chr9
✅ Chromosome renamed: ALL.chr10.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.atomized.vcf.gz → Contigs: ['chr10'], First record CHROM: chr10
✅ Chromosome renamed: ALL.chr11.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.atomized.vcf.gz → Contigs: ['chr11'], First record CHROM: chr11
✅ Chromosome renamed: ALL.chr12.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.atomized.vcf.gz → Contigs: ['chr12'], First record CHROM: chr12
✅ Chromosome renamed: ALL.chr13.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.atomized.vcf.gz → Contigs: ['chr13'], First record CHROM: chr13
✅ Chromosome renamed: ALL.chr14.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.atomized.vcf.gz → Contigs: ['chr14'], First record CHROM: chr14
✅ Chromosome renamed: ALL.chr15.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.atomized.vcf.gz → Contigs: ['chr15'], First record CHROM: chr15
✅ Chromosome renamed: ALL.chr16.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.atomized.vcf.gz → Contigs: ['chr16'], First record CHROM: chr16
✅ Chromosome renamed: ALL.chr17.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.atomized.vcf.gz → Contigs: ['chr17'], First record CHROM: chr17
✅ Chromosome renamed: ALL.chr18.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.atomized.vcf.gz → Contigs: ['chr18'], First record CHROM: chr18
✅ Chromosome renamed: ALL.chr19.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.atomized.vcf.gz → Contigs: ['chr19'], First record CHROM: chr19
✅ Chromosome renamed: ALL.chr20.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.atomized.vcf.gz → Contigs: ['chr20'], First record CHROM: chr20
✅ Chromosome renamed: ALL.chr21.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.atomized.vcf.gz → Contigs: ['chr21'], First record CHROM: chr21
✅ Chromosome renamed: ALL.chr22.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.atomized.vcf.gz → Contigs: ['chr22'], First record CHROM: chr22
✅ Chromosome renamed: ALL.chrX.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.atomized.vcf.gz → Contigs: ['chrX'], First record CHROM: chrX

In [4]:
import pysam

vcf = pysam.VariantFile("/grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/data/1000_Genomes_on_GRCh38/vcf/ALL.chr1.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz")

# Check header contigs
print("Header contigs:")
print(list(vcf.header.contigs))

# Check actual CHROM values in records
for rec in vcf.fetch():
    print("Example CHROM in record:", rec.contig)
    break

Header contigs:
['1']
Example CHROM in record: 1

In [43]:
# Split SpliceVarDB x ClinVar splicing SNVs VCF file based on chromosome, and create a bed region file for each split VCF file.
split_splicing_variants = False

if split_splicing_variants:
    import pandas as pd
    import subprocess
    import pooch
    
    filtered_intersect_snv = pd.read_csv('splicevardb_x_clinvar_snv.csv')
    
    # Remove rows with missing simplified clinical significance
    filtered_intersect_snv = filtered_intersect_snv[~filtered_intersect_snv['CLNSIG_simplified'].isna()]
    
    # Ensure 'chr' values are strings and start with 'chr' (e.g., 'chr1' instead of '1')
    filtered_intersect_snv['chr'] = filtered_intersect_snv['chr'].astype(str)
    
    reference = pooch.retrieve(
        url="https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/GRCh38_reference_genome/GRCh38_full_analysis_set_plus_decoy_hla.fa",
        known_hash=None,
        progressbar=True,
    )
    reference = reference + ".bgz"
        
    unique_chrs = filtered_intersect_snv['chr'].unique()
    
    # Loop through chromosomes
    unique_chrs = filtered_intersect_snv['chr'].unique()
    
    for chromosome in unique_chrs:
        chr_df = filtered_intersect_snv[filtered_intersect_snv['chr'] == chromosome]
        base_name = f"splicevardb_x_clinvar_snv_{chromosome}"
        raw_vcf = f"./data/splicevardb_x_clinvar/{base_name}.vcf"
        compressed_vcf = f"{raw_vcf}.gz"
        atomized_vcf = f"./data/splicevardb_x_clinvar/{base_name}.atomized.vcf.gz"
    
        # Write minimal VCF
        with open(raw_vcf, "w") as f:
            f.write('##fileformat=VCFv4.1\n')
            f.write('##source=splicevardb.ipynb\n') 
            f.write('##reference=GRCh38\n')
            f.write('##ID=<Description="ClinVar Variation ID">\n')
            f.write(f"##contig=<ID={chromosome}>\n")
            f.write('#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\n')
            for _, row in chr_df.iterrows():
                info_str = ""  # Empty INFO field
                f.write(f"{row['chr']}\t{row['pos']}\t{row['clinvar_id']}\t{row['ref']}\t{row['alt']}\t{row['qual']}\t{row['filter']}\t{info_str}\n")
    
        # Compress and index raw VCF
        print(f"Compressing {raw_vcf}")
        subprocess.run(["bgzip", "-k", raw_vcf], check=True)
    
        print(f"Indexing {compressed_vcf}")
        subprocess.run(["tabix", "-p", "vcf", compressed_vcf], check=True)
    
        # Normalize using reference
        print(f"Normalizing {compressed_vcf}")
        subprocess.run([
            "bcftools", "norm",
            "-a", "-c", "s", "-m-any",
            "-f", reference,
            "-o", atomized_vcf,
            compressed_vcf
        ], check=True)
    
        print(f"Indexing {atomized_vcf}")
        subprocess.run(["tabix", "-p", "vcf", atomized_vcf], check=True)

        vcf_data = pd.read_csv(atomized_vcf, 
                        sep='\t',
                        comment='#', # Skip comment lines starting with #
                        names=['CHROM', 'POS', 'ID', 'REF', 'ALT', 'QUAL', 'FILTER', 'INFO']) # Standard VCF columns


        site_bed = pd.DataFrame()
        site_bed['CHROM'] = vcf_data['CHROM']
        site_bed['start'] = vcf_data['POS']
        site_bed['end'] = vcf_data['POS'] + 1  # This is weird, ask Jack
        display(site_bed.head())
        padding = 15000
        site_bed.iloc[:,1] = site_bed.iloc[:,1]-padding
        site_bed.iloc[:,2] = site_bed.iloc[:,2]+padding
        # Save BED in same naming convention
        bed_output_path = f"./data/splicevardb_x_clinvar/{base_name}_region_bed.bed"
        site_bed.to_csv(bed_output_path, sep='\t', header=False, index=False)
        print(f"Saved padded BED to {bed_output_path}")

Compressing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr1.vcf
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr1.vcf.gz
Normalizing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr1.vcf.gz
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr1.atomized.vcf.gz

Lines   total/split/joined/realigned/removed/skipped:	560/0/0/0/0/0
REF/ALT total/modified/added:  	560/0/0

  CHROM    start      end
0  chr1  1049450  1049451
1  chr1  1051638  1051639
2  chr1  3244069  3244070
3  chr1  3244097  3244098
4  chr1  3244101  3244102

Saved padded BED to ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr1_region_bed.bed
Compressing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr10.vcf
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr10.vcf.gz
Normalizing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr10.vcf.gz
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr10.atomized.vcf.gz

Lines   total/split/joined/realigned/removed/skipped:	311/0/0/0/0/0
REF/ALT total/modified/added:  	311/0/0

   CHROM    start      end
0  chr10   236835   236836
1  chr10   247438   247439
2  chr10   999021   999022
3  chr10  1014252  1014253
4  chr10  1014270  1014271

Saved padded BED to ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr10_region_bed.bed
Compressing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr11.vcf

Lines   total/split/joined/realigned/removed/skipped:	478/0/0/0/0/0
REF/ALT total/modified/added:  	478/0/0

Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr11.vcf.gz
Normalizing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr11.vcf.gz
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr11.atomized.vcf.gz

   CHROM    start      end
0  chr11   687906   687907
1  chr11   822474   822475
2  chr11   837938   837939
3  chr11   837945   837946
4  chr11  2165787  2165788

Saved padded BED to ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr11_region_bed.bed
Compressing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr12.vcf
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr12.vcf.gz
Normalizing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr12.vcf.gz
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr12.atomized.vcf.gz

Lines   total/split/joined/realigned/removed/skipped:	419/0/0/0/0/0
REF/ALT total/modified/added:  	419/0/0

   CHROM   start     end
0  chr12  861347  861348
1  chr12  889165  889166
2  chr12  889173  889174
3  chr12  889185  889186
4  chr12  889193  889194

Saved padded BED to ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr12_region_bed.bed
Compressing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr13.vcf
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr13.vcf.gz
Normalizing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr13.vcf.gz

Lines   total/split/joined/realigned/removed/skipped:	315/0/0/0/0/0
REF/ALT total/modified/added:  	315/0/0

Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr13.atomized.vcf.gz

   CHROM     start       end
0  chr13  20583033  20583034
1  chr13  20631053  20631054
2  chr13  23295435  23295436
3  chr13  23295460  23295461
4  chr13  25571592  25571593

Saved padded BED to ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr13_region_bed.bed
Compressing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr14.vcf
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr14.vcf.gz
Normalizing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr14.vcf.gz
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr14.atomized.vcf.gz

Lines   total/split/joined/realigned/removed/skipped:	238/0/0/0/0/0
REF/ALT total/modified/added:  	238/0/0

   CHROM     start       end
0  chr14  20390748  20390749
1  chr14  20448090  20448091
2  chr14  20448141  20448142
3  chr14  20448159  20448160
4  chr14  20448161  20448162

Saved padded BED to ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr14_region_bed.bed
Compressing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr15.vcf
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr15.vcf.gz
Normalizing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr15.vcf.gz
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr15.atomized.vcf.gz

Lines   total/split/joined/realigned/removed/skipped:	356/0/0/0/0/0
REF/ALT total/modified/added:  	356/0/0

   CHROM     start       end
0  chr15  27986615  27986616
1  chr15  27986633  27986634
2  chr15  27989583  27989584
3  chr15  27989601  27989602
4  chr15  27989649  27989650

Saved padded BED to ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr15_region_bed.bed
Compressing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr16.vcf
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr16.vcf.gz
Normalizing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr16.vcf.gz
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr16.atomized.vcf.gz

Lines   total/split/joined/realigned/removed/skipped:	470/0/0/0/0/0
REF/ALT total/modified/added:  	470/0/0

   CHROM    start      end
0  chr16   220651   220652
1  chr16   220675   220676
2  chr16   220725   220726
3  chr16   575870   575871
4  chr16  1314280  1314281

Saved padded BED to ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr16_region_bed.bed
Compressing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr17.vcf
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr17.vcf.gz
Normalizing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr17.vcf.gz
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr17.atomized.vcf.gz

Lines   total/split/joined/realigned/removed/skipped:	897/0/0/0/0/0
REF/ALT total/modified/added:  	897/0/0

   CHROM   start     end
0  chr17  710536  710537
1  chr17  710537  710538
2  chr17  710548  710549
3  chr17  710590  710591
4  chr17  710602  710603

Saved padded BED to ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr17_region_bed.bed
Compressing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr18.vcf
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr18.vcf.gz
Normalizing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr18.vcf.gz
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr18.atomized.vcf.gz

Lines   total/split/joined/realigned/removed/skipped:	79/0/0/0/0/0
REF/ALT total/modified/added:  	79/0/0

   CHROM    start      end
0  chr18   265318   265319
1  chr18   694294   694295
2  chr18   694316   694317
3  chr18  2923778  2923779
4  chr18  5395685  5395686

Saved padded BED to ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr18_region_bed.bed
Compressing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr19.vcf
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr19.vcf.gz
Normalizing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr19.vcf.gz
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr19.atomized.vcf.gz

Lines   total/split/joined/realigned/removed/skipped:	311/0/0/0/0/0
REF/ALT total/modified/added:  	311/0/0

   CHROM    start      end
0  chr19   536266   536267
1  chr19   875245   875246
2  chr19  1105814  1105815
3  chr19  1218416  1218417
4  chr19  1218424  1218425

Saved padded BED to ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr19_region_bed.bed
Compressing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr2.vcf
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr2.vcf.gz
Normalizing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr2.vcf.gz
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr2.atomized.vcf.gz

Lines   total/split/joined/realigned/removed/skipped:	775/0/0/0/0/0
REF/ALT total/modified/added:  	775/0/0

  CHROM    start      end
0  chr2  1259409  1259410
1  chr2  1259412  1259413
2  chr2  1308552  1308553
3  chr2  3613345  3613346
4  chr2  3613401  3613402

Saved padded BED to ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr2_region_bed.bed

Lines   total/split/joined/realigned/removed/skipped:	122/0/0/0/0/0
REF/ALT total/modified/added:  	122/0/0

Compressing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr20.vcf
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr20.vcf.gz
Normalizing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr20.vcf.gz
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr20.atomized.vcf.gz

   CHROM    start      end
0  chr20   492282   492283
1  chr20   495702   495703
2  chr20  2659698  2659699
3  chr20  2660590  2660591
4  chr20  3230258  3230259

Saved padded BED to ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr20_region_bed.bed
Compressing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr21.vcf
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr21.vcf.gz
Normalizing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr21.vcf.gz
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr21.atomized.vcf.gz

Lines   total/split/joined/realigned/removed/skipped:	75/0/0/0/0/0
REF/ALT total/modified/added:  	75/0/0

   CHROM     start       end
0  chr21  15762901  15762902
1  chr21  25975945  25975946
2  chr21  25976005  25976006
3  chr21  25976039  25976040
4  chr21  25976059  25976060

Saved padded BED to ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr21_region_bed.bed
Compressing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr22.vcf
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr22.vcf.gz
Normalizing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr22.vcf.gz
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr22.atomized.vcf.gz

Lines   total/split/joined/realigned/removed/skipped:	123/0/0/0/0/0
REF/ALT total/modified/added:  	123/0/0

   CHROM     start       end
0  chr22  17104729  17104730
1  chr22  17600027  17600028
2  chr22  17600050  17600051
3  chr22  17600057  17600058
4  chr22  17600059  17600060

Saved padded BED to ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr22_region_bed.bed
Compressing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr3.vcf
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr3.vcf.gz
Normalizing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr3.vcf.gz
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr3.atomized.vcf.gz

Lines   total/split/joined/realigned/removed/skipped:	589/0/0/0/0/0
REF/ALT total/modified/added:  	589/0/0

  CHROM    start      end
0  chr3  4376305  4376306
1  chr3  4376338  4376339
2  chr3  4376340  4376341
3  chr3  4376342  4376343
4  chr3  4376365  4376366

Saved padded BED to ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr3_region_bed.bed
Compressing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr4.vcf
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr4.vcf.gz
Normalizing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr4.vcf.gz
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr4.atomized.vcf.gz

Lines   total/split/joined/realigned/removed/skipped:	175/0/0/0/0/0
REF/ALT total/modified/added:  	175/0/0

  CHROM   start     end
0  chr4  635860  635861
1  chr4  635892  635893
2  chr4  635908  635909
3  chr4  635909  635910
4  chr4  635922  635923

Saved padded BED to ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr4_region_bed.bed
Compressing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr5.vcf
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr5.vcf.gz
Normalizing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr5.vcf.gz
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr5.atomized.vcf.gz

Lines   total/split/joined/realigned/removed/skipped:	332/0/0/0/0/0
REF/ALT total/modified/added:  	332/0/0

  CHROM   start     end
0  chr5  155361  155362
1  chr5  155427  155428
2  chr5  223470  223471
3  chr5  223480  223481
4  chr5  223521  223522

Saved padded BED to ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr5_region_bed.bed
Compressing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr6.vcf
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr6.vcf.gz
Normalizing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr6.vcf.gz

Lines   total/split/joined/realigned/removed/skipped:	250/0/0/0/0/0
REF/ALT total/modified/added:  	250/0/0

Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr6.atomized.vcf.gz

  CHROM    start      end
0  chr6  3110802  3110803
1  chr6  6195841  6195842
2  chr6  6195859  6195860
3  chr6  6195876  6195877
4  chr6  7562781  7562782

Saved padded BED to ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr6_region_bed.bed
Compressing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr7.vcf
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr7.vcf.gz
Normalizing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr7.vcf.gz
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr7.atomized.vcf.gz

Lines   total/split/joined/realigned/removed/skipped:	533/0/0/0/0/0
REF/ALT total/modified/added:  	533/0/0

  CHROM   start     end
0  chr7  208951  208952
1  chr7  872451  872452
2  chr7  872489  872490
3  chr7  872519  872520
4  chr7  872520  872521

Saved padded BED to ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr7_region_bed.bed
Compressing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr8.vcf
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr8.vcf.gz
Normalizing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr8.vcf.gz

Lines   total/split/joined/realigned/removed/skipped:	228/0/0/0/0/0
REF/ALT total/modified/added:  	228/0/0

Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr8.atomized.vcf.gz

  CHROM    start      end
0  chr8  1869201  1869202
1  chr8  1898481  1898482
2  chr8  1898498  1898499
3  chr8  6431567  6431568
4  chr8  6499839  6499840

Saved padded BED to ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr8_region_bed.bed
Compressing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr9.vcf
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr9.vcf.gz
Normalizing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr9.vcf.gz
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr9.atomized.vcf.gz

Lines   total/split/joined/realigned/removed/skipped:	343/0/0/0/0/0
REF/ALT total/modified/added:  	343/0/0

  CHROM   start     end
0  chr9  332378  332379
1  chr9  332381  332382
2  chr9  332468  332469
3  chr9  332472  332473
4  chr9  386311  386312

Saved padded BED to ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr9_region_bed.bed
Compressing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chrX.vcf
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chrX.vcf.gz
Normalizing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chrX.vcf.gz
Indexing ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chrX.atomized.vcf.gz

Lines   total/split/joined/realigned/removed/skipped:	511/0/0/0/0/0
REF/ALT total/modified/added:  	511/0/0

  CHROM    start      end
0  chrX   640852   640853
1  chrX  3615805  3615806
2  chrX  3615831  3615832
3  chrX  3615856  3615857
4  chrX  3615864  3615865

Saved padded BED to ./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chrX_region_bed.bed

In [42]:
# Split 5' and 3' ss annotation files based on chromosome

split_annotation_file = True
anno_dir = './data/annotation/'

if split_annotation_file:
    import pandas as pd
    p5_bed_file = pd.read_csv('./data/annotation/p5_bed.bed', sep='\t')
    p3_bed_file = pd.read_csv('./data/annotation/p3_bed.bed', sep='\t')
    
    chromosomes = [f"chr{i}" for i in range(1, 23)] + ["chrX"]
    
    # Loop through each chromosome
    for chrom in chromosomes:
        print(f"\n🔄 Splitting annotation file for chromosome: {chrom}...")
        chr_p5 = p5_bed_file[p5_bed_file['#CHROM'] == chrom]
        chr_p3 = p3_bed_file[p3_bed_file['#CHROM'] == chrom]
        chr_p5.to_csv(os.path.join(anno_dir, f"p5_{chrom}_bed.bed"), index=False, sep='\t', header=False)
        chr_p3.to_csv(os.path.join(anno_dir, f"p3_{chrom}_bed.bed"), index=False, sep='\t', header=False)

🔄 Splitting annotation file for chromosome: chr1...

🔄 Splitting annotation file for chromosome: chr2...

🔄 Splitting annotation file for chromosome: chr3...

🔄 Splitting annotation file for chromosome: chr4...

🔄 Splitting annotation file for chromosome: chr5...

🔄 Splitting annotation file for chromosome: chr6...

🔄 Splitting annotation file for chromosome: chr7...

🔄 Splitting annotation file for chromosome: chr8...

🔄 Splitting annotation file for chromosome: chr9...

🔄 Splitting annotation file for chromosome: chr10...

🔄 Splitting annotation file for chromosome: chr11...

🔄 Splitting annotation file for chromosome: chr12...

🔄 Splitting annotation file for chromosome: chr13...

🔄 Splitting annotation file for chromosome: chr14...

🔄 Splitting annotation file for chromosome: chr15...

🔄 Splitting annotation file for chromosome: chr16...

🔄 Splitting annotation file for chromosome: chr17...

🔄 Splitting annotation file for chromosome: chr18...

🔄 Splitting annotation file for chromosome: chr19...

🔄 Splitting annotation file for chromosome: chr20...

🔄 Splitting annotation file for chromosome: chr21...

🔄 Splitting annotation file for chromosome: chr22...

🔄 Splitting annotation file for chromosome: chrX...

In [43]:
for name, path in vcf_paths.items():
    vcf_in = pysam.VariantFile(path, "r")
    print(list(vcf_in.header.contigs))

['1']
['2']
['3']
['4']
['5']
['6']
['7']
['8']
['9']
['10']
['11']
['12']
['13']
['14']
['15']
['16']
['17']
['18']
['19']
['20']
['21']
['22']
['X']

In [15]:
import os
from pathlib import Path
from sys import path
from src.dataset import SpliceHapDataset

# Define paths based on your previous pipeline
data_dir = Path("./data/gvl")
data_dir.mkdir(parents=True, exist_ok=True)

# Define input files (assuming chr22 based on example)
reference_bgz = Path(f"{reference_path}.bgz")
region_bed_path = Path("./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr22_region_bed.bed")
annotation_bed_path = [
    ("3pss", "./data/annotation/p3_chr22_bed.bed"),
    ("5pss", "./data/annotation/p5_chr22_bed.bed")
]
variant_path = Path("./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_chr22.atomized.vcf.gz")  # Curate splicing snvs
hap_pgen_path = Path("./data/1000_Genomes_on_GRCh38/vcf/ALL.chr22.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.atomized.vcf.gz")  # 1KGP haplotype variants
dataset_path = data_dir / "chr22_dataset.gvl"

# Construct the dataset
from src.dataset import SpliceHapDataset  # Assuming this is where the class is located

dataset = SpliceHapDataset.build_from_files_with_matching_sites(
    reference_path=str(reference_bgz),
    region_bed_path=str(region_bed_path),
    hap_pgen_path=str(hap_pgen_path),
    variant_path=str(variant_path),
    window_size=50,
    context_size=5000,
    bed_paths=annotation_bed_path,
    dataset_path=str(dataset_path),
    ploidy=2,
    deduplicate=False,
    remake_dataset=True,  # Set True for initial run
    num_workers=0,
    enable_profiling=True,
    enable_cache=True
)

# Output the shape of the dataset
dataset_shape = dataset.shape()
dataset_shape

2025-05-30 15:26:43.195 | INFO     | genvarloader._dataset._write:write:75 - Writing dataset to data/gvl/chr22_dataset.gvl
2025-05-30 15:26:43.196 | INFO     | genvarloader._dataset._write:write:82 - Found existing GVL store, overwriting.
2025-05-30 15:26:43.246 | INFO     | genvarloader._dataset._write:write:147 - Using 2548 samples.
2025-05-30 15:26:43.247 | INFO     | genvarloader._dataset._write:write:153 - Writing genotypes.
2025-05-30 15:26:43.252 | INFO     | genvarloader._dataset._write:_write_from_vcf:230 - VCF genoray index is invalid, writing
Reading records: 100%|████████████████████████████████████████| 1059079/1059079 [00:16<00:00, 63736.46 record/s]
2025-05-30 15:27:10.513 | INFO     | genoray._vcf:_load_index:1028 - Loading genoray index.
Processing genotypes for 123 regions on contig chr22: 100%|██████████████| 123/123 [00:30<00:00,  4.05 region/s]
2025-05-30 15:27:42.953 | INFO     | genvarloader._dataset._write:write:177 - Finished writing.
2025-05-30 15:27:42.960 | INFO     | genvarloader._dataset._impl:open:192 - Loading reference genome into memory. This typically has a modest memory footprint (a few GB) and greatly improves performance.
2025-05-30 15:27:43.173 | INFO     | genvarloader._dataset._reconstruct:from_path:183 - Loading variant data.
2025-05-30 15:27:43.254 | INFO     | genvarloader._dataset._impl:open:278 - Opened dataset:
GVL store at data/gvl/chr22_dataset.gvl
Is subset: False
# of regions: 123
# of samples: 2548
Output length: ragged
Jitter: 0 (max: 0)
Deterministic: True
Sequence type: reference [haplotypes] annotated variants
Active tracks: None
Tracks available: None

Reading records: 100%|███████████████████████████████████████████████| 123/123 [00:00<00:00, 244039.45 record/s]
/grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/src/dataset.py:239: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  self.matching_indices = self.gvl.rows.with_row_count().filter(pl.col("region_idx") == pl.col("site_idx")).get_column("row_nr").to_numpy()

(123, 2548, 2)

In [16]:
# reference = '/grid/kinney/home/zhliu/.cache/pooch/296ca04ba1df562072adc4c76f64cfb9-GRCh38_full_analysis_set_plus_decoy_hla.fa.bgz'
# region_bed_path = '../data/splicing/splicevardb_x_clinvar_snv_ch22_region_bed.bed'
# atomized_variants = '/grid/kinney/home/zhliu/.cache/pooch/ALL.chr22.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.renamed.atomized.vcf.gz'
# snps = '../data/splicing/splicevardb_x_clinvar_snv_ch22.atomized.vcf.gz'
# annotation_bed_path = [('3pss', '../data/p3_chr22_bed.bed'), ('5pss', '../data/p5_chr22_bed.bed')]

# dataset1 = SpliceHapDataset.build_from_files_with_matching_sites(
#     reference_path=reference,
#     region_bed_path=region_bed_path,
#     hap_pgen_path=atomized_variants,
#     variant_path=snps,
#     window_size=50,
#     context_size=5000,
#     bed_paths=annotation_bed_path,
#     dataset_path='./test_full_chr22_dataset_var_bed.gvl',
#     ploidy=2,
#     deduplicate=False,
#     remake_dataset=False, #this needs to be set to true the first time the dataset is built but takes a bit so should be set to False in future loads (unless you have changed a specification file)
#     num_workers=0, #adding workers to the dataset this makes batched loading faster (but has not been extensively tested) can be set to 0 for no workers
#     enable_profiling=False, # this should be set to true if you want to analyze the performance of the dataset. should be false for normal use
#     enable_cache=True, #If this is set to True the loading of sequential variants will be wildly faster but the initial loading will be slower. If you are going to be loading non-sequential variants then set this to False.
#     )


# dataset1.shape()

2025-05-30 15:33:15.194 | INFO     | genvarloader._dataset._impl:open:192 - Loading reference genome into memory. This typically has a modest memory footprint (a few GB) and greatly improves performance.
2025-05-30 15:33:15.344 | INFO     | genvarloader._dataset._reconstruct:from_path:183 - Loading variant data.
2025-05-30 15:33:15.400 | INFO     | genvarloader._dataset._impl:open:278 - Opened dataset:
GVL store at test_full_chr22_dataset_var_bed.gvl
Is subset: False
# of regions: 123
# of samples: 2548
Output length: ragged
Jitter: 0 (max: 0)
Deterministic: True
Sequence type: reference [haplotypes] annotated variants
Active tracks: None
Tracks available: None

Reading records: 100%|███████████████████████████████████████████████| 123/123 [00:00<00:00, 226669.33 record/s]
/grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/src/dataset.py:239: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  self.matching_indices = self.gvl.rows.with_row_count().filter(pl.col("region_idx") == pl.col("site_idx")).get_column("row_nr").to_numpy()

(123, 2548, 2)

In [28]:
# # Test loading on a batch of variants
# dataset.enable_profiling = False
# dataset.enable_cache = True
# dataset_output =next(dataset.batch_iter(2000))

# # Test loading on a batch of variants
# dataset1.enable_profiling = False
# dataset1.enable_cache = True
# dataset1_output =next(dataset1.batch_iter(2000))

In [30]:
# for idx in range(len(dataset_output)):
#     print((dataset1_output[idx] == dataset2_output[idx]).all())

True
True
True
True
True
True
True
True
True
True
True

In [44]:
import os
from pathlib import Path
from src.dataset import SpliceHapDataset

# Define root paths
data_dir = Path("./data/gvl")
data_dir.mkdir(parents=True, exist_ok=True)
reference_bgz = Path(f"{reference_path}.bgz")  # From earlier step

# List of chromosomes to process
chromosomes = [f"chr{i}" for i in range(1, 23)] + ["chrX"]

# Loop through each chromosome
for chrom in chromosomes:
    print(f"\n🔄 Processing {chrom}...")

    variant_path = Path(f"./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_{chrom}.atomized.vcf.gz")
    hap_pgen_path = Path(f"./data/1000_Genomes_on_GRCh38/vcf/ALL.{chrom}.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.atomized.vcf.gz")
    region_bed_path = Path(f"./data/splicevardb_x_clinvar/splicevardb_x_clinvar_snv_{chrom}_region_bed.bed")
    annotation_bed_path = [
        ("3pss", f"./data/annotation/p3_{chrom}_bed.bed"),
        ("5pss", f"./data/annotation/p5_{chrom}_bed.bed")
    ]
    dataset_path = data_dir / f"{chrom}_dataset.gvl"

    # ⏭️ Skip if output already exists
    if dataset_path.exists():
        print(f"⏭️ {chrom} → Output already exists, skipping...")
        continue

    # Check if all required files exist
    required_files = [variant_path, hap_pgen_path, region_bed_path] + [Path(p[1]) for p in annotation_bed_path]
    if not all(f.exists() for f in required_files):
        print(f"⚠️ Missing files for {chrom}, skipping...")
        continue

    # Build the dataset
    dataset = SpliceHapDataset.build_from_files_with_matching_sites(
        reference_path=str(reference_bgz),
        region_bed_path=str(region_bed_path),
        hap_pgen_path=str(hap_pgen_path),
        variant_path=str(variant_path),
        window_size=50,
        context_size=5000,
        bed_paths=annotation_bed_path,
        dataset_path=str(dataset_path),
        ploidy=2,
        deduplicate=False,
        remake_dataset=True,  # Set False in future to avoid rebuilding
        num_workers=0,
        enable_profiling=True,
        enable_cache=True
    )

    shape = dataset.shape()
    print(f"✅ {chrom} → Dataset shape: {shape}")

🔄 Processing chr1...

2025-05-30 16:20:18.793 | INFO     | genvarloader._dataset._write:write:75 - Writing dataset to data/gvl/chr1_dataset.gvl
2025-05-30 16:20:18.872 | INFO     | genvarloader._dataset._write:write:147 - Using 2548 samples.
2025-05-30 16:20:18.873 | INFO     | genvarloader._dataset._write:write:153 - Writing genotypes.
2025-05-30 16:20:18.879 | INFO     | genvarloader._dataset._write:_write_from_vcf:230 - VCF genoray index is invalid, writing
Reading records: 100%|████████████████████████████████████████| 6191833/6191833 [01:27<00:00, 70613.15 record/s]
2025-05-30 16:22:38.457 | INFO     | genoray._vcf:_load_index:1028 - Loading genoray index.
Processing genotypes for 560 regions on contig chr1: 100%|███████████████| 560/560 [02:15<00:00,  4.13 region/s]
2025-05-30 16:25:01.518 | INFO     | genvarloader._dataset._write:write:177 - Finished writing.
2025-05-30 16:25:01.523 | INFO     | genvarloader._dataset._impl:open:192 - Loading reference genome into memory. This typically has a modest memory footprint (a few GB) and greatly improves performance.
2025-05-30 16:25:04.004 | INFO     | genvarloader._dataset._reconstruct:from_path:183 - Loading variant data.
2025-05-30 16:25:04.408 | INFO     | genvarloader._dataset._impl:open:278 - Opened dataset:
GVL store at data/gvl/chr1_dataset.gvl
Is subset: False
# of regions: 560
# of samples: 2548
Output length: ragged
Jitter: 0 (max: 0)
Deterministic: True
Sequence type: reference [haplotypes] annotated variants
Active tracks: None
Tracks available: None

Reading records: 100%|███████████████████████████████████████████████| 560/560 [00:00<00:00, 344400.33 record/s]
/grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/src/dataset.py:239: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  self.matching_indices = self.gvl.rows.with_row_count().filter(pl.col("region_idx") == pl.col("site_idx")).get_column("row_nr").to_numpy()
2025-05-30 16:25:04.988 | INFO     | genvarloader._dataset._write:write:75 - Writing dataset to data/gvl/chr2_dataset.gvl
2025-05-30 16:25:05.027 | INFO     | genvarloader._dataset._write:write:147 - Using 2548 samples.
2025-05-30 16:25:05.027 | INFO     | genvarloader._dataset._write:write:153 - Writing genotypes.
2025-05-30 16:25:05.034 | INFO     | genvarloader._dataset._write:_write_from_vcf:230 - VCF genoray index is invalid, writing

✅ chr1 → Dataset shape: (560, 2548, 2)

🔄 Processing chr2...

Reading records: 100%|████████████████████████████████████████| 6790551/6790551 [01:34<00:00, 71684.81 record/s]
2025-05-30 16:27:35.829 | INFO     | genoray._vcf:_load_index:1028 - Loading genoray index.
Processing genotypes for 775 regions on contig chr2: 100%|███████████████| 775/775 [03:09<00:00,  4.09 region/s]
2025-05-30 16:30:53.732 | INFO     | genvarloader._dataset._write:write:177 - Finished writing.
2025-05-30 16:30:53.736 | INFO     | genvarloader._dataset._impl:open:192 - Loading reference genome into memory. This typically has a modest memory footprint (a few GB) and greatly improves performance.
2025-05-30 16:30:54.323 | INFO     | genvarloader._dataset._reconstruct:from_path:183 - Loading variant data.
2025-05-30 16:30:54.740 | INFO     | genvarloader._dataset._impl:open:278 - Opened dataset:
GVL store at data/gvl/chr2_dataset.gvl
Is subset: False
# of regions: 775
# of samples: 2548
Output length: ragged
Jitter: 0 (max: 0)
Deterministic: True
Sequence type: reference [haplotypes] annotated variants
Active tracks: None
Tracks available: None

Reading records: 100%|███████████████████████████████████████████████| 775/775 [00:00<00:00, 357482.20 record/s]
/grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/src/dataset.py:239: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  self.matching_indices = self.gvl.rows.with_row_count().filter(pl.col("region_idx") == pl.col("site_idx")).get_column("row_nr").to_numpy()
2025-05-30 16:30:55.065 | INFO     | genvarloader._dataset._write:write:75 - Writing dataset to data/gvl/chr3_dataset.gvl
2025-05-30 16:30:55.133 | INFO     | genvarloader._dataset._write:write:147 - Using 2548 samples.
2025-05-30 16:30:55.134 | INFO     | genvarloader._dataset._write:write:153 - Writing genotypes.
2025-05-30 16:30:55.140 | INFO     | genvarloader._dataset._write:_write_from_vcf:230 - VCF genoray index is invalid, writing

✅ chr2 → Dataset shape: (775, 2548, 2)

🔄 Processing chr3...

Reading records: 100%|████████████████████████████████████████| 5641493/5641493 [01:21<00:00, 69149.79 record/s]
2025-05-30 16:32:58.782 | INFO     | genoray._vcf:_load_index:1028 - Loading genoray index.
Processing genotypes for 589 regions on contig chr3: 100%|███████████████| 589/589 [02:12<00:00,  4.46 region/s]
2025-05-30 16:35:17.640 | INFO     | genvarloader._dataset._write:write:177 - Finished writing.
2025-05-30 16:35:17.644 | INFO     | genvarloader._dataset._impl:open:192 - Loading reference genome into memory. This typically has a modest memory footprint (a few GB) and greatly improves performance.
2025-05-30 16:35:18.147 | INFO     | genvarloader._dataset._reconstruct:from_path:183 - Loading variant data.
2025-05-30 16:35:18.488 | INFO     | genvarloader._dataset._impl:open:278 - Opened dataset:
GVL store at data/gvl/chr3_dataset.gvl
Is subset: False
# of regions: 589
# of samples: 2548
Output length: ragged
Jitter: 0 (max: 0)
Deterministic: True
Sequence type: reference [haplotypes] annotated variants
Active tracks: None
Tracks available: None

Reading records: 100%|███████████████████████████████████████████████| 589/589 [00:00<00:00, 336206.46 record/s]
/grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/src/dataset.py:239: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  self.matching_indices = self.gvl.rows.with_row_count().filter(pl.col("region_idx") == pl.col("site_idx")).get_column("row_nr").to_numpy()
2025-05-30 16:35:18.782 | INFO     | genvarloader._dataset._write:write:75 - Writing dataset to data/gvl/chr4_dataset.gvl
2025-05-30 16:35:18.848 | INFO     | genvarloader._dataset._write:write:147 - Using 2548 samples.
2025-05-30 16:35:18.848 | INFO     | genvarloader._dataset._write:write:153 - Writing genotypes.
2025-05-30 16:35:18.854 | INFO     | genvarloader._dataset._write:_write_from_vcf:230 - VCF genoray index is invalid, writing

✅ chr3 → Dataset shape: (589, 2548, 2)

🔄 Processing chr4...

Reading records: 100%|████████████████████████████████████████| 5477810/5477810 [01:15<00:00, 72472.80 record/s]
2025-05-30 16:37:17.800 | INFO     | genoray._vcf:_load_index:1028 - Loading genoray index.
Processing genotypes for 175 regions on contig chr4: 100%|███████████████| 175/175 [00:43<00:00,  4.02 region/s]
2025-05-30 16:38:07.777 | INFO     | genvarloader._dataset._write:write:177 - Finished writing.
2025-05-30 16:38:07.782 | INFO     | genvarloader._dataset._impl:open:192 - Loading reference genome into memory. This typically has a modest memory footprint (a few GB) and greatly improves performance.
2025-05-30 16:38:08.316 | INFO     | genvarloader._dataset._reconstruct:from_path:183 - Loading variant data.
2025-05-30 16:38:08.714 | INFO     | genvarloader._dataset._impl:open:278 - Opened dataset:
GVL store at data/gvl/chr4_dataset.gvl
Is subset: False
# of regions: 175
# of samples: 2548
Output length: ragged
Jitter: 0 (max: 0)
Deterministic: True
Sequence type: reference [haplotypes] annotated variants
Active tracks: None
Tracks available: None

Reading records: 100%|███████████████████████████████████████████████| 175/175 [00:00<00:00, 301810.53 record/s]
/grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/src/dataset.py:239: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  self.matching_indices = self.gvl.rows.with_row_count().filter(pl.col("region_idx") == pl.col("site_idx")).get_column("row_nr").to_numpy()
2025-05-30 16:38:09.379 | INFO     | genvarloader._dataset._write:write:75 - Writing dataset to data/gvl/chr5_dataset.gvl
2025-05-30 16:38:09.446 | INFO     | genvarloader._dataset._write:write:147 - Using 2548 samples.
2025-05-30 16:38:09.446 | INFO     | genvarloader._dataset._write:write:153 - Writing genotypes.
2025-05-30 16:38:09.452 | INFO     | genvarloader._dataset._write:_write_from_vcf:230 - VCF genoray index is invalid, writing

✅ chr4 → Dataset shape: (175, 2548, 2)

🔄 Processing chr5...

Reading records: 100%|████████████████████████████████████████| 5115036/5115036 [01:10<00:00, 72165.81 record/s]
2025-05-30 16:40:01.075 | INFO     | genoray._vcf:_load_index:1028 - Loading genoray index.
Processing genotypes for 332 regions on contig chr5:  30%|████▊           | 99/332 [00:25<00:53,  4.38 region/s]2025-05-30 16:40:32.513 | WARNING  | genvarloader._dataset._write:_write_from_vcf:287 - A region has no variants for any sample. This could be expected depending on the region lengths and source of variants. However, this can also be caused by a mismatch between the reference genome used for the BED file coordinates and the one used for the variants. This warning will not be shown again.
Processing genotypes for 332 regions on contig chr5: 100%|███████████████| 332/332 [01:18<00:00,  4.23 region/s]
2025-05-30 16:41:25.514 | INFO     | genvarloader._dataset._write:write:177 - Finished writing.
2025-05-30 16:41:25.518 | INFO     | genvarloader._dataset._impl:open:192 - Loading reference genome into memory. This typically has a modest memory footprint (a few GB) and greatly improves performance.
2025-05-30 16:41:26.034 | INFO     | genvarloader._dataset._reconstruct:from_path:183 - Loading variant data.
2025-05-30 16:41:26.339 | INFO     | genvarloader._dataset._impl:open:278 - Opened dataset:
GVL store at data/gvl/chr5_dataset.gvl
Is subset: False
# of regions: 332
# of samples: 2548
Output length: ragged
Jitter: 0 (max: 0)
Deterministic: True
Sequence type: reference [haplotypes] annotated variants
Active tracks: None
Tracks available: None

Reading records: 100%|███████████████████████████████████████████████| 332/332 [00:00<00:00, 301017.93 record/s]
/grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/src/dataset.py:239: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  self.matching_indices = self.gvl.rows.with_row_count().filter(pl.col("region_idx") == pl.col("site_idx")).get_column("row_nr").to_numpy()
2025-05-30 16:41:26.585 | INFO     | genvarloader._dataset._write:write:75 - Writing dataset to data/gvl/chr6_dataset.gvl
2025-05-30 16:41:26.636 | INFO     | genvarloader._dataset._write:write:147 - Using 2548 samples.
2025-05-30 16:41:26.636 | INFO     | genvarloader._dataset._write:write:153 - Writing genotypes.
2025-05-30 16:41:26.642 | INFO     | genvarloader._dataset._write:_write_from_vcf:230 - VCF genoray index is invalid, writing

✅ chr5 → Dataset shape: (332, 2548, 2)

🔄 Processing chr6...

Reading records: 100%|████████████████████████████████████████| 4863337/4863337 [01:08<00:00, 71250.97 record/s]
2025-05-30 16:43:13.756 | INFO     | genoray._vcf:_load_index:1028 - Loading genoray index.
Processing genotypes for 250 regions on contig chr6: 100%|███████████████| 250/250 [00:59<00:00,  4.19 region/s]
2025-05-30 16:44:19.171 | INFO     | genvarloader._dataset._write:write:177 - Finished writing.
2025-05-30 16:44:19.176 | INFO     | genvarloader._dataset._impl:open:192 - Loading reference genome into memory. This typically has a modest memory footprint (a few GB) and greatly improves performance.
2025-05-30 16:44:19.803 | INFO     | genvarloader._dataset._reconstruct:from_path:183 - Loading variant data.
2025-05-30 16:44:20.039 | INFO     | genvarloader._dataset._impl:open:278 - Opened dataset:
GVL store at data/gvl/chr6_dataset.gvl
Is subset: False
# of regions: 250
# of samples: 2548
Output length: ragged
Jitter: 0 (max: 0)
Deterministic: True
Sequence type: reference [haplotypes] annotated variants
Active tracks: None
Tracks available: None

Reading records: 100%|███████████████████████████████████████████████| 250/250 [00:00<00:00, 284552.51 record/s]
/grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/src/dataset.py:239: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  self.matching_indices = self.gvl.rows.with_row_count().filter(pl.col("region_idx") == pl.col("site_idx")).get_column("row_nr").to_numpy()
2025-05-30 16:44:20.332 | INFO     | genvarloader._dataset._write:write:75 - Writing dataset to data/gvl/chr7_dataset.gvl
2025-05-30 16:44:20.390 | INFO     | genvarloader._dataset._write:write:147 - Using 2548 samples.
2025-05-30 16:44:20.391 | INFO     | genvarloader._dataset._write:write:153 - Writing genotypes.
2025-05-30 16:44:20.397 | INFO     | genvarloader._dataset._write:_write_from_vcf:230 - VCF genoray index is invalid, writing

✅ chr6 → Dataset shape: (250, 2548, 2)

🔄 Processing chr7...

Reading records: 100%|████████████████████████████████████████| 4511408/4511408 [01:04<00:00, 70219.20 record/s]
2025-05-30 16:45:57.860 | INFO     | genoray._vcf:_load_index:1028 - Loading genoray index.
Processing genotypes for 533 regions on contig chr7: 100%|███████████████| 533/533 [02:58<00:00,  2.99 region/s]
2025-05-30 16:49:01.341 | INFO     | genvarloader._dataset._write:write:177 - Finished writing.
2025-05-30 16:49:01.346 | INFO     | genvarloader._dataset._impl:open:192 - Loading reference genome into memory. This typically has a modest memory footprint (a few GB) and greatly improves performance.
2025-05-30 16:49:01.880 | INFO     | genvarloader._dataset._reconstruct:from_path:183 - Loading variant data.
2025-05-30 16:49:02.198 | INFO     | genvarloader._dataset._impl:open:278 - Opened dataset:
GVL store at data/gvl/chr7_dataset.gvl
Is subset: False
# of regions: 533
# of samples: 2548
Output length: ragged
Jitter: 0 (max: 0)
Deterministic: True
Sequence type: reference [haplotypes] annotated variants
Active tracks: None
Tracks available: None

Reading records: 100%|███████████████████████████████████████████████| 533/533 [00:00<00:00, 348110.25 record/s]
/grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/src/dataset.py:239: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  self.matching_indices = self.gvl.rows.with_row_count().filter(pl.col("region_idx") == pl.col("site_idx")).get_column("row_nr").to_numpy()
2025-05-30 16:49:02.435 | INFO     | genvarloader._dataset._write:write:75 - Writing dataset to data/gvl/chr8_dataset.gvl
2025-05-30 16:49:02.477 | INFO     | genvarloader._dataset._write:write:147 - Using 2548 samples.
2025-05-30 16:49:02.477 | INFO     | genvarloader._dataset._write:write:153 - Writing genotypes.
2025-05-30 16:49:02.483 | INFO     | genvarloader._dataset._write:_write_from_vcf:230 - VCF genoray index is invalid, writing

✅ chr7 → Dataset shape: (533, 2548, 2)

🔄 Processing chr8...

Reading records: 100%|████████████████████████████████████████| 4425449/4425449 [01:04<00:00, 68849.76 record/s]
2025-05-30 16:50:40.130 | INFO     | genoray._vcf:_load_index:1028 - Loading genoray index.
Processing genotypes for 228 regions on contig chr8: 100%|███████████████| 228/228 [00:58<00:00,  3.87 region/s]
2025-05-30 16:51:44.221 | INFO     | genvarloader._dataset._write:write:177 - Finished writing.
2025-05-30 16:51:44.226 | INFO     | genvarloader._dataset._impl:open:192 - Loading reference genome into memory. This typically has a modest memory footprint (a few GB) and greatly improves performance.
2025-05-30 16:51:44.706 | INFO     | genvarloader._dataset._reconstruct:from_path:183 - Loading variant data.
2025-05-30 16:51:44.911 | INFO     | genvarloader._dataset._impl:open:278 - Opened dataset:
GVL store at data/gvl/chr8_dataset.gvl
Is subset: False
# of regions: 228
# of samples: 2548
Output length: ragged
Jitter: 0 (max: 0)
Deterministic: True
Sequence type: reference [haplotypes] annotated variants
Active tracks: None
Tracks available: None

Reading records: 100%|███████████████████████████████████████████████| 228/228 [00:00<00:00, 279130.56 record/s]
/grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/src/dataset.py:239: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  self.matching_indices = self.gvl.rows.with_row_count().filter(pl.col("region_idx") == pl.col("site_idx")).get_column("row_nr").to_numpy()
2025-05-30 16:51:45.148 | INFO     | genvarloader._dataset._write:write:75 - Writing dataset to data/gvl/chr9_dataset.gvl
2025-05-30 16:51:45.184 | INFO     | genvarloader._dataset._write:write:147 - Using 2548 samples.
2025-05-30 16:51:45.185 | INFO     | genvarloader._dataset._write:write:153 - Writing genotypes.
2025-05-30 16:51:45.190 | INFO     | genvarloader._dataset._write:_write_from_vcf:230 - VCF genoray index is invalid, writing

✅ chr8 → Dataset shape: (228, 2548, 2)

🔄 Processing chr9...

Reading records: 100%|████████████████████████████████████████| 3384360/3384360 [00:46<00:00, 72398.24 record/s]
2025-05-30 16:52:59.042 | INFO     | genoray._vcf:_load_index:1028 - Loading genoray index.
Processing genotypes for 343 regions on contig chr9: 100%|███████████████| 343/343 [01:29<00:00,  3.83 region/s]
2025-05-30 16:54:32.661 | INFO     | genvarloader._dataset._write:write:177 - Finished writing.
2025-05-30 16:54:32.666 | INFO     | genvarloader._dataset._impl:open:192 - Loading reference genome into memory. This typically has a modest memory footprint (a few GB) and greatly improves performance.
2025-05-30 16:54:33.147 | INFO     | genvarloader._dataset._reconstruct:from_path:183 - Loading variant data.
2025-05-30 16:54:33.317 | INFO     | genvarloader._dataset._impl:open:278 - Opened dataset:
GVL store at data/gvl/chr9_dataset.gvl
Is subset: False
# of regions: 343
# of samples: 2548
Output length: ragged
Jitter: 0 (max: 0)
Deterministic: True
Sequence type: reference [haplotypes] annotated variants
Active tracks: None
Tracks available: None

Reading records: 100%|███████████████████████████████████████████████| 343/343 [00:00<00:00, 302809.15 record/s]
/grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/src/dataset.py:239: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  self.matching_indices = self.gvl.rows.with_row_count().filter(pl.col("region_idx") == pl.col("site_idx")).get_column("row_nr").to_numpy()
2025-05-30 16:54:33.591 | INFO     | genvarloader._dataset._write:write:75 - Writing dataset to data/gvl/chr10_dataset.gvl
2025-05-30 16:54:33.630 | INFO     | genvarloader._dataset._write:write:147 - Using 2548 samples.
2025-05-30 16:54:33.630 | INFO     | genvarloader._dataset._write:write:153 - Writing genotypes.
2025-05-30 16:54:33.636 | INFO     | genvarloader._dataset._write:_write_from_vcf:230 - VCF genoray index is invalid, writing

✅ chr9 → Dataset shape: (343, 2548, 2)

🔄 Processing chr10...

Reading records: 100%|████████████████████████████████████████| 3874259/3874259 [00:54<00:00, 71048.06 record/s]
2025-05-30 16:55:59.280 | INFO     | genoray._vcf:_load_index:1028 - Loading genoray index.
Processing genotypes for 311 regions on contig chr10: 100%|██████████████| 311/311 [01:17<00:00,  4.03 region/s]
2025-05-30 16:57:21.041 | INFO     | genvarloader._dataset._write:write:177 - Finished writing.
2025-05-30 16:57:21.045 | INFO     | genvarloader._dataset._impl:open:192 - Loading reference genome into memory. This typically has a modest memory footprint (a few GB) and greatly improves performance.
2025-05-30 16:57:21.522 | INFO     | genvarloader._dataset._reconstruct:from_path:183 - Loading variant data.
2025-05-30 16:57:21.804 | INFO     | genvarloader._dataset._impl:open:278 - Opened dataset:
GVL store at data/gvl/chr10_dataset.gvl
Is subset: False
# of regions: 311
# of samples: 2548
Output length: ragged
Jitter: 0 (max: 0)
Deterministic: True
Sequence type: reference [haplotypes] annotated variants
Active tracks: None
Tracks available: None

Reading records: 100%|███████████████████████████████████████████████| 311/311 [00:00<00:00, 253681.16 record/s]
/grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/src/dataset.py:239: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  self.matching_indices = self.gvl.rows.with_row_count().filter(pl.col("region_idx") == pl.col("site_idx")).get_column("row_nr").to_numpy()
2025-05-30 16:57:22.399 | INFO     | genvarloader._dataset._write:write:75 - Writing dataset to data/gvl/chr11_dataset.gvl
2025-05-30 16:57:22.473 | INFO     | genvarloader._dataset._write:write:147 - Using 2548 samples.
2025-05-30 16:57:22.473 | INFO     | genvarloader._dataset._write:write:153 - Writing genotypes.
2025-05-30 16:57:22.480 | INFO     | genvarloader._dataset._write:_write_from_vcf:230 - VCF genoray index is invalid, writing

✅ chr10 → Dataset shape: (311, 2548, 2)

🔄 Processing chr11...

Reading records: 100%|████████████████████████████████████████| 3881791/3881791 [00:54<00:00, 70848.44 record/s]
2025-05-30 16:58:48.373 | INFO     | genoray._vcf:_load_index:1028 - Loading genoray index.
Processing genotypes for 478 regions on contig chr11: 100%|██████████████| 478/478 [01:54<00:00,  4.19 region/s]
2025-05-30 17:00:47.323 | INFO     | genvarloader._dataset._write:write:177 - Finished writing.
2025-05-30 17:00:47.328 | INFO     | genvarloader._dataset._impl:open:192 - Loading reference genome into memory. This typically has a modest memory footprint (a few GB) and greatly improves performance.
2025-05-30 17:00:47.982 | INFO     | genvarloader._dataset._reconstruct:from_path:183 - Loading variant data.
2025-05-30 17:00:48.205 | INFO     | genvarloader._dataset._impl:open:278 - Opened dataset:
GVL store at data/gvl/chr11_dataset.gvl
Is subset: False
# of regions: 478
# of samples: 2548
Output length: ragged
Jitter: 0 (max: 0)
Deterministic: True
Sequence type: reference [haplotypes] annotated variants
Active tracks: None
Tracks available: None

Reading records: 100%|███████████████████████████████████████████████| 478/478 [00:00<00:00, 277453.27 record/s]
/grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/src/dataset.py:239: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  self.matching_indices = self.gvl.rows.with_row_count().filter(pl.col("region_idx") == pl.col("site_idx")).get_column("row_nr").to_numpy()
2025-05-30 17:00:48.469 | INFO     | genvarloader._dataset._write:write:75 - Writing dataset to data/gvl/chr12_dataset.gvl
2025-05-30 17:00:48.517 | INFO     | genvarloader._dataset._write:write:147 - Using 2548 samples.
2025-05-30 17:00:48.517 | INFO     | genvarloader._dataset._write:write:153 - Writing genotypes.
2025-05-30 17:00:48.523 | INFO     | genvarloader._dataset._write:_write_from_vcf:230 - VCF genoray index is invalid, writing

✅ chr11 → Dataset shape: (478, 2548, 2)

🔄 Processing chr12...

Reading records: 100%|████████████████████████████████████████| 3745465/3745465 [01:02<00:00, 59479.51 record/s]
2025-05-30 17:02:23.226 | INFO     | genoray._vcf:_load_index:1028 - Loading genoray index.
Processing genotypes for 419 regions on contig chr12: 100%|██████████████| 419/419 [01:43<00:00,  4.06 region/s]
2025-05-30 17:04:11.801 | INFO     | genvarloader._dataset._write:write:177 - Finished writing.
2025-05-30 17:04:11.806 | INFO     | genvarloader._dataset._impl:open:192 - Loading reference genome into memory. This typically has a modest memory footprint (a few GB) and greatly improves performance.
2025-05-30 17:04:12.277 | INFO     | genvarloader._dataset._reconstruct:from_path:183 - Loading variant data.
2025-05-30 17:04:12.479 | INFO     | genvarloader._dataset._impl:open:278 - Opened dataset:
GVL store at data/gvl/chr12_dataset.gvl
Is subset: False
# of regions: 419
# of samples: 2548
Output length: ragged
Jitter: 0 (max: 0)
Deterministic: True
Sequence type: reference [haplotypes] annotated variants
Active tracks: None
Tracks available: None

Reading records: 100%|███████████████████████████████████████████████| 419/419 [00:00<00:00, 323529.71 record/s]
/grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/src/dataset.py:239: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  self.matching_indices = self.gvl.rows.with_row_count().filter(pl.col("region_idx") == pl.col("site_idx")).get_column("row_nr").to_numpy()
2025-05-30 17:04:12.762 | INFO     | genvarloader._dataset._write:write:75 - Writing dataset to data/gvl/chr13_dataset.gvl
2025-05-30 17:04:12.795 | INFO     | genvarloader._dataset._write:write:147 - Using 2548 samples.
2025-05-30 17:04:12.796 | INFO     | genvarloader._dataset._write:write:153 - Writing genotypes.
2025-05-30 17:04:12.801 | INFO     | genvarloader._dataset._write:_write_from_vcf:230 - VCF genoray index is invalid, writing

✅ chr12 → Dataset shape: (419, 2548, 2)

🔄 Processing chr13...

Reading records: 100%|████████████████████████████████████████| 2760845/2760845 [00:39<00:00, 69435.23 record/s]
2025-05-30 17:05:13.411 | INFO     | genoray._vcf:_load_index:1028 - Loading genoray index.
Processing genotypes for 315 regions on contig chr13: 100%|██████████████| 315/315 [01:11<00:00,  4.44 region/s]
2025-05-30 17:06:27.769 | INFO     | genvarloader._dataset._write:write:177 - Finished writing.
2025-05-30 17:06:27.774 | INFO     | genvarloader._dataset._impl:open:192 - Loading reference genome into memory. This typically has a modest memory footprint (a few GB) and greatly improves performance.
2025-05-30 17:06:28.165 | INFO     | genvarloader._dataset._reconstruct:from_path:183 - Loading variant data.
2025-05-30 17:06:28.292 | INFO     | genvarloader._dataset._impl:open:278 - Opened dataset:
GVL store at data/gvl/chr13_dataset.gvl
Is subset: False
# of regions: 315
# of samples: 2548
Output length: ragged
Jitter: 0 (max: 0)
Deterministic: True
Sequence type: reference [haplotypes] annotated variants
Active tracks: None
Tracks available: None

Reading records: 100%|███████████████████████████████████████████████| 315/315 [00:00<00:00, 241228.00 record/s]
/grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/src/dataset.py:239: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  self.matching_indices = self.gvl.rows.with_row_count().filter(pl.col("region_idx") == pl.col("site_idx")).get_column("row_nr").to_numpy()
2025-05-30 17:06:28.510 | INFO     | genvarloader._dataset._write:write:75 - Writing dataset to data/gvl/chr14_dataset.gvl
2025-05-30 17:06:28.544 | INFO     | genvarloader._dataset._write:write:147 - Using 2548 samples.
2025-05-30 17:06:28.544 | INFO     | genvarloader._dataset._write:write:153 - Writing genotypes.
2025-05-30 17:06:28.549 | INFO     | genvarloader._dataset._write:_write_from_vcf:230 - VCF genoray index is invalid, writing

✅ chr13 → Dataset shape: (315, 2548, 2)

🔄 Processing chr14...

Reading records: 100%|████████████████████████████████████████| 2548903/2548903 [00:38<00:00, 66656.20 record/s]
2025-05-30 17:07:30.057 | INFO     | genoray._vcf:_load_index:1028 - Loading genoray index.
Processing genotypes for 238 regions on contig chr14: 100%|██████████████| 238/238 [01:02<00:00,  3.79 region/s]
2025-05-30 17:08:36.357 | INFO     | genvarloader._dataset._write:write:177 - Finished writing.
2025-05-30 17:08:36.362 | INFO     | genvarloader._dataset._impl:open:192 - Loading reference genome into memory. This typically has a modest memory footprint (a few GB) and greatly improves performance.
2025-05-30 17:08:36.800 | INFO     | genvarloader._dataset._reconstruct:from_path:183 - Loading variant data.
2025-05-30 17:08:36.944 | INFO     | genvarloader._dataset._impl:open:278 - Opened dataset:
GVL store at data/gvl/chr14_dataset.gvl
Is subset: False
# of regions: 238
# of samples: 2548
Output length: ragged
Jitter: 0 (max: 0)
Deterministic: True
Sequence type: reference [haplotypes] annotated variants
Active tracks: None
Tracks available: None

Reading records: 100%|███████████████████████████████████████████████| 238/238 [00:00<00:00, 235046.94 record/s]
/grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/src/dataset.py:239: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  self.matching_indices = self.gvl.rows.with_row_count().filter(pl.col("region_idx") == pl.col("site_idx")).get_column("row_nr").to_numpy()
2025-05-30 17:08:37.463 | INFO     | genvarloader._dataset._write:write:75 - Writing dataset to data/gvl/chr15_dataset.gvl
2025-05-30 17:08:37.500 | INFO     | genvarloader._dataset._write:write:147 - Using 2548 samples.
2025-05-30 17:08:37.501 | INFO     | genvarloader._dataset._write:write:153 - Writing genotypes.
2025-05-30 17:08:37.506 | INFO     | genvarloader._dataset._write:_write_from_vcf:230 - VCF genoray index is invalid, writing

✅ chr14 → Dataset shape: (238, 2548, 2)

🔄 Processing chr15...

Reading records: 100%|████████████████████████████████████████| 2301453/2301453 [00:38<00:00, 59461.91 record/s]
2025-05-30 17:09:35.314 | INFO     | genoray._vcf:_load_index:1028 - Loading genoray index.
Processing genotypes for 356 regions on contig chr15: 100%|██████████████| 356/356 [01:23<00:00,  4.26 region/s]
2025-05-30 17:11:01.799 | INFO     | genvarloader._dataset._write:write:177 - Finished writing.
2025-05-30 17:11:01.804 | INFO     | genvarloader._dataset._impl:open:192 - Loading reference genome into memory. This typically has a modest memory footprint (a few GB) and greatly improves performance.
2025-05-30 17:11:02.250 | INFO     | genvarloader._dataset._reconstruct:from_path:183 - Loading variant data.
2025-05-30 17:11:02.418 | INFO     | genvarloader._dataset._impl:open:278 - Opened dataset:
GVL store at data/gvl/chr15_dataset.gvl
Is subset: False
# of regions: 356
# of samples: 2548
Output length: ragged
Jitter: 0 (max: 0)
Deterministic: True
Sequence type: reference [haplotypes] annotated variants
Active tracks: None
Tracks available: None

Reading records: 100%|███████████████████████████████████████████████| 356/356 [00:00<00:00, 299713.41 record/s]
/grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/src/dataset.py:239: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  self.matching_indices = self.gvl.rows.with_row_count().filter(pl.col("region_idx") == pl.col("site_idx")).get_column("row_nr").to_numpy()
2025-05-30 17:11:02.675 | INFO     | genvarloader._dataset._write:write:75 - Writing dataset to data/gvl/chr16_dataset.gvl

✅ chr15 → Dataset shape: (356, 2548, 2)

🔄 Processing chr16...

2025-05-30 17:11:02.894 | INFO     | genvarloader._dataset._write:write:147 - Using 2548 samples.
2025-05-30 17:11:02.895 | INFO     | genvarloader._dataset._write:write:153 - Writing genotypes.
2025-05-30 17:11:02.901 | INFO     | genvarloader._dataset._write:_write_from_vcf:230 - VCF genoray index is invalid, writing
Reading records: 100%|████████████████████████████████████████| 2548920/2548920 [00:36<00:00, 69868.75 record/s]
2025-05-30 17:12:04.628 | INFO     | genoray._vcf:_load_index:1028 - Loading genoray index.
Processing genotypes for 470 regions on contig chr16:  27%|███▊          | 128/470 [00:39<01:07,  5.03 region/s]2025-05-30 17:12:47.272 | WARNING  | genvarloader._dataset._write:_write_from_vcf:287 - A region has no variants for any sample. This could be expected depending on the region lengths and source of variants. However, this can also be caused by a mismatch between the reference genome used for the BED file coordinates and the one used for the variants. This warning will not be shown again.
Processing genotypes for 470 regions on contig chr16: 100%|██████████████| 470/470 [02:08<00:00,  3.67 region/s]
2025-05-30 17:14:15.931 | INFO     | genvarloader._dataset._write:write:177 - Finished writing.
2025-05-30 17:14:15.935 | INFO     | genvarloader._dataset._impl:open:192 - Loading reference genome into memory. This typically has a modest memory footprint (a few GB) and greatly improves performance.
2025-05-30 17:14:16.318 | INFO     | genvarloader._dataset._reconstruct:from_path:183 - Loading variant data.
2025-05-30 17:14:16.453 | INFO     | genvarloader._dataset._impl:open:278 - Opened dataset:
GVL store at data/gvl/chr16_dataset.gvl
Is subset: False
# of regions: 470
# of samples: 2548
Output length: ragged
Jitter: 0 (max: 0)
Deterministic: True
Sequence type: reference [haplotypes] annotated variants
Active tracks: None
Tracks available: None

Reading records: 100%|███████████████████████████████████████████████| 470/470 [00:00<00:00, 304733.79 record/s]
/grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/src/dataset.py:239: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  self.matching_indices = self.gvl.rows.with_row_count().filter(pl.col("region_idx") == pl.col("site_idx")).get_column("row_nr").to_numpy()
2025-05-30 17:14:16.722 | INFO     | genvarloader._dataset._write:write:75 - Writing dataset to data/gvl/chr17_dataset.gvl
2025-05-30 17:14:16.904 | INFO     | genvarloader._dataset._write:write:147 - Using 2548 samples.
2025-05-30 17:14:16.905 | INFO     | genvarloader._dataset._write:write:153 - Writing genotypes.
2025-05-30 17:14:16.910 | INFO     | genvarloader._dataset._write:_write_from_vcf:230 - VCF genoray index is invalid, writing

✅ chr16 → Dataset shape: (470, 2548, 2)

🔄 Processing chr17...

Reading records: 100%|████████████████████████████████████████| 2209149/2209149 [00:31<00:00, 69800.81 record/s]
2025-05-30 17:15:05.130 | INFO     | genoray._vcf:_load_index:1028 - Loading genoray index.
Processing genotypes for 897 regions on contig chr17: 100%|██████████████| 897/897 [03:13<00:00,  4.65 region/s]
2025-05-30 17:18:21.100 | INFO     | genvarloader._dataset._write:write:177 - Finished writing.
2025-05-30 17:18:21.104 | INFO     | genvarloader._dataset._impl:open:192 - Loading reference genome into memory. This typically has a modest memory footprint (a few GB) and greatly improves performance.
2025-05-30 17:18:21.514 | INFO     | genvarloader._dataset._reconstruct:from_path:183 - Loading variant data.
2025-05-30 17:18:21.696 | INFO     | genvarloader._dataset._impl:open:278 - Opened dataset:
GVL store at data/gvl/chr17_dataset.gvl
Is subset: False
# of regions: 897
# of samples: 2548
Output length: ragged
Jitter: 0 (max: 0)
Deterministic: True
Sequence type: reference [haplotypes] annotated variants
Active tracks: None
Tracks available: None

Reading records: 100%|███████████████████████████████████████████████| 897/897 [00:00<00:00, 366981.14 record/s]
/grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/src/dataset.py:239: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  self.matching_indices = self.gvl.rows.with_row_count().filter(pl.col("region_idx") == pl.col("site_idx")).get_column("row_nr").to_numpy()
2025-05-30 17:18:22.112 | INFO     | genvarloader._dataset._write:write:75 - Writing dataset to data/gvl/chr18_dataset.gvl
2025-05-30 17:18:22.179 | INFO     | genvarloader._dataset._write:write:147 - Using 2548 samples.
2025-05-30 17:18:22.179 | INFO     | genvarloader._dataset._write:write:153 - Writing genotypes.
2025-05-30 17:18:22.184 | INFO     | genvarloader._dataset._write:_write_from_vcf:230 - VCF genoray index is invalid, writing

✅ chr17 → Dataset shape: (897, 2548, 2)

🔄 Processing chr18...

Reading records: 100%|████████████████████████████████████████| 2189529/2189529 [00:31<00:00, 68764.87 record/s]
2025-05-30 17:19:10.657 | INFO     | genoray._vcf:_load_index:1028 - Loading genoray index.
Processing genotypes for 79 regions on contig chr18: 100%|█████████████████| 79/79 [00:20<00:00,  3.94 region/s]
2025-05-30 17:19:33.339 | INFO     | genvarloader._dataset._write:write:177 - Finished writing.
2025-05-30 17:19:33.343 | INFO     | genvarloader._dataset._impl:open:192 - Loading reference genome into memory. This typically has a modest memory footprint (a few GB) and greatly improves performance.
2025-05-30 17:19:33.771 | INFO     | genvarloader._dataset._reconstruct:from_path:183 - Loading variant data.
2025-05-30 17:19:33.881 | INFO     | genvarloader._dataset._impl:open:278 - Opened dataset:
GVL store at data/gvl/chr18_dataset.gvl
Is subset: False
# of regions: 79
# of samples: 2548
Output length: ragged
Jitter: 0 (max: 0)
Deterministic: True
Sequence type: reference [haplotypes] annotated variants
Active tracks: None
Tracks available: None

Reading records: 100%|█████████████████████████████████████████████████| 79/79 [00:00<00:00, 163065.95 record/s]
/grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/src/dataset.py:239: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  self.matching_indices = self.gvl.rows.with_row_count().filter(pl.col("region_idx") == pl.col("site_idx")).get_column("row_nr").to_numpy()
2025-05-30 17:19:34.106 | INFO     | genvarloader._dataset._write:write:75 - Writing dataset to data/gvl/chr19_dataset.gvl
2025-05-30 17:19:34.144 | INFO     | genvarloader._dataset._write:write:147 - Using 2548 samples.
2025-05-30 17:19:34.145 | INFO     | genvarloader._dataset._write:write:153 - Writing genotypes.
2025-05-30 17:19:34.151 | INFO     | genvarloader._dataset._write:_write_from_vcf:230 - VCF genoray index is invalid, writing

✅ chr18 → Dataset shape: (79, 2548, 2)

🔄 Processing chr19...

Reading records: 100%|████████████████████████████████████████| 1738824/1738824 [00:28<00:00, 60410.17 record/s]
2025-05-30 17:20:17.587 | INFO     | genoray._vcf:_load_index:1028 - Loading genoray index.
Processing genotypes for 311 regions on contig chr19: 100%|██████████████| 311/311 [01:26<00:00,  3.60 region/s]
2025-05-30 17:21:46.695 | INFO     | genvarloader._dataset._write:write:177 - Finished writing.
2025-05-30 17:21:46.699 | INFO     | genvarloader._dataset._impl:open:192 - Loading reference genome into memory. This typically has a modest memory footprint (a few GB) and greatly improves performance.
2025-05-30 17:21:47.054 | INFO     | genvarloader._dataset._reconstruct:from_path:183 - Loading variant data.
2025-05-30 17:21:47.152 | INFO     | genvarloader._dataset._impl:open:278 - Opened dataset:
GVL store at data/gvl/chr19_dataset.gvl
Is subset: False
# of regions: 311
# of samples: 2548
Output length: ragged
Jitter: 0 (max: 0)
Deterministic: True
Sequence type: reference [haplotypes] annotated variants
Active tracks: None
Tracks available: None

Reading records: 100%|███████████████████████████████████████████████| 311/311 [00:00<00:00, 292932.53 record/s]
/grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/src/dataset.py:239: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  self.matching_indices = self.gvl.rows.with_row_count().filter(pl.col("region_idx") == pl.col("site_idx")).get_column("row_nr").to_numpy()
2025-05-30 17:21:47.395 | INFO     | genvarloader._dataset._write:write:75 - Writing dataset to data/gvl/chr20_dataset.gvl
2025-05-30 17:21:47.467 | INFO     | genvarloader._dataset._write:write:147 - Using 2548 samples.
2025-05-30 17:21:47.468 | INFO     | genvarloader._dataset._write:write:153 - Writing genotypes.
2025-05-30 17:21:47.472 | INFO     | genvarloader._dataset._write:_write_from_vcf:230 - VCF genoray index is invalid, writing

✅ chr19 → Dataset shape: (311, 2548, 2)

🔄 Processing chr20...

Reading records: 100%|████████████████████████████████████████| 1817492/1817492 [00:26<00:00, 68391.32 record/s]
2025-05-30 17:22:32.207 | INFO     | genoray._vcf:_load_index:1028 - Loading genoray index.
Processing genotypes for 122 regions on contig chr20: 100%|██████████████| 122/122 [00:30<00:00,  3.98 region/s]
2025-05-30 17:23:05.100 | INFO     | genvarloader._dataset._write:write:177 - Finished writing.
2025-05-30 17:23:05.105 | INFO     | genvarloader._dataset._impl:open:192 - Loading reference genome into memory. This typically has a modest memory footprint (a few GB) and greatly improves performance.
2025-05-30 17:23:05.431 | INFO     | genvarloader._dataset._reconstruct:from_path:183 - Loading variant data.
2025-05-30 17:23:05.538 | INFO     | genvarloader._dataset._impl:open:278 - Opened dataset:
GVL store at data/gvl/chr20_dataset.gvl
Is subset: False
# of regions: 122
# of samples: 2548
Output length: ragged
Jitter: 0 (max: 0)
Deterministic: True
Sequence type: reference [haplotypes] annotated variants
Active tracks: None
Tracks available: None

Reading records: 100%|███████████████████████████████████████████████| 122/122 [00:00<00:00, 174405.28 record/s]
/grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/src/dataset.py:239: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  self.matching_indices = self.gvl.rows.with_row_count().filter(pl.col("region_idx") == pl.col("site_idx")).get_column("row_nr").to_numpy()
2025-05-30 17:23:05.796 | INFO     | genvarloader._dataset._write:write:75 - Writing dataset to data/gvl/chr21_dataset.gvl
2025-05-30 17:23:05.836 | INFO     | genvarloader._dataset._write:write:147 - Using 2548 samples.
2025-05-30 17:23:05.837 | INFO     | genvarloader._dataset._write:write:153 - Writing genotypes.
2025-05-30 17:23:05.841 | INFO     | genvarloader._dataset._write:_write_from_vcf:230 - VCF genoray index is invalid, writing

✅ chr20 → Dataset shape: (122, 2548, 2)

🔄 Processing chr21...

Reading records: 100%|████████████████████████████████████████| 1045269/1045269 [00:14<00:00, 70923.22 record/s]
2025-05-30 17:23:30.000 | INFO     | genoray._vcf:_load_index:1028 - Loading genoray index.
Processing genotypes for 75 regions on contig chr21:  32%|█████▍           | 24/75 [00:06<00:14,  3.61 region/s]2025-05-30 17:23:37.923 | WARNING  | genvarloader._dataset._write:_write_from_vcf:287 - A region has no variants for any sample. This could be expected depending on the region lengths and source of variants. However, this can also be caused by a mismatch between the reference genome used for the BED file coordinates and the one used for the variants. This warning will not be shown again.
Processing genotypes for 75 regions on contig chr21: 100%|█████████████████| 75/75 [00:17<00:00,  4.18 region/s]
2025-05-30 17:23:49.426 | INFO     | genvarloader._dataset._write:write:177 - Finished writing.
2025-05-30 17:23:49.430 | INFO     | genvarloader._dataset._impl:open:192 - Loading reference genome into memory. This typically has a modest memory footprint (a few GB) and greatly improves performance.
2025-05-30 17:23:49.801 | INFO     | genvarloader._dataset._reconstruct:from_path:183 - Loading variant data.
2025-05-30 17:23:49.857 | INFO     | genvarloader._dataset._impl:open:278 - Opened dataset:
GVL store at data/gvl/chr21_dataset.gvl
Is subset: False
# of regions: 75
# of samples: 2548
Output length: ragged
Jitter: 0 (max: 0)
Deterministic: True
Sequence type: reference [haplotypes] annotated variants
Active tracks: None
Tracks available: None

Reading records: 100%|█████████████████████████████████████████████████| 75/75 [00:00<00:00, 160087.94 record/s]
/grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/src/dataset.py:239: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  self.matching_indices = self.gvl.rows.with_row_count().filter(pl.col("region_idx") == pl.col("site_idx")).get_column("row_nr").to_numpy()
2025-05-30 17:23:50.204 | INFO     | genvarloader._dataset._write:write:75 - Writing dataset to data/gvl/chr22_dataset.gvl
2025-05-30 17:23:50.204 | INFO     | genvarloader._dataset._write:write:82 - Found existing GVL store, overwriting.
2025-05-30 17:23:50.246 | INFO     | genvarloader._dataset._write:write:147 - Using 2548 samples.
2025-05-30 17:23:50.247 | INFO     | genvarloader._dataset._write:write:153 - Writing genotypes.
2025-05-30 17:23:50.252 | INFO     | genoray._vcf:_load_index:1028 - Loading genoray index.

✅ chr21 → Dataset shape: (75, 2548, 2)

🔄 Processing chr22...

Processing genotypes for 123 regions on contig chr22: 100%|██████████████| 123/123 [00:29<00:00,  4.20 region/s]
2025-05-30 17:24:21.195 | INFO     | genvarloader._dataset._write:write:177 - Finished writing.
2025-05-30 17:24:21.199 | INFO     | genvarloader._dataset._impl:open:192 - Loading reference genome into memory. This typically has a modest memory footprint (a few GB) and greatly improves performance.
2025-05-30 17:24:21.252 | INFO     | genvarloader._dataset._reconstruct:from_path:183 - Loading variant data.
2025-05-30 17:24:21.332 | INFO     | genvarloader._dataset._impl:open:278 - Opened dataset:
GVL store at data/gvl/chr22_dataset.gvl
Is subset: False
# of regions: 123
# of samples: 2548
Output length: ragged
Jitter: 0 (max: 0)
Deterministic: True
Sequence type: reference [haplotypes] annotated variants
Active tracks: None
Tracks available: None

Reading records: 100%|███████████████████████████████████████████████| 123/123 [00:00<00:00, 261082.69 record/s]
/grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/src/dataset.py:239: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  self.matching_indices = self.gvl.rows.with_row_count().filter(pl.col("region_idx") == pl.col("site_idx")).get_column("row_nr").to_numpy()
2025-05-30 17:24:21.655 | INFO     | genvarloader._dataset._write:write:75 - Writing dataset to data/gvl/chrX_dataset.gvl
2025-05-30 17:24:21.700 | INFO     | genvarloader._dataset._write:write:147 - Using 2548 samples.
2025-05-30 17:24:21.700 | INFO     | genvarloader._dataset._write:write:153 - Writing genotypes.
2025-05-30 17:24:21.704 | INFO     | genvarloader._dataset._write:_write_from_vcf:230 - VCF genoray index is invalid, writing

✅ chr22 → Dataset shape: (123, 2548, 2)

🔄 Processing chrX...

Reading records: 100%|██████████████████████████████████████████| 106963/106963 [00:01<00:00, 65933.28 record/s]
2025-05-30 17:24:24.047 | INFO     | genoray._vcf:_load_index:1028 - Loading genoray index.
Processing genotypes for 511 regions on contig chrX:   0%|                 | 1/511 [00:00<02:51,  2.97 region/s]2025-05-30 17:24:24.492 | WARNING  | genvarloader._dataset._write:_write_from_vcf:287 - A region has no variants for any sample. This could be expected depending on the region lengths and source of variants. However, this can also be caused by a mismatch between the reference genome used for the BED file coordinates and the one used for the variants. This warning will not be shown again.
Processing genotypes for 511 regions on contig chrX: 100%|██████████████| 511/511 [00:03<00:00, 167.87 region/s]
2025-05-30 17:24:27.584 | INFO     | genvarloader._dataset._write:write:177 - Finished writing.
2025-05-30 17:24:27.588 | INFO     | genvarloader._dataset._impl:open:192 - Loading reference genome into memory. This typically has a modest memory footprint (a few GB) and greatly improves performance.
2025-05-30 17:24:28.135 | INFO     | genvarloader._dataset._reconstruct:from_path:183 - Loading variant data.
2025-05-30 17:24:28.142 | INFO     | genvarloader._dataset._impl:open:278 - Opened dataset:
GVL store at data/gvl/chrX_dataset.gvl
Is subset: False
# of regions: 511
# of samples: 2548
Output length: ragged
Jitter: 0 (max: 0)
Deterministic: True
Sequence type: reference [haplotypes] annotated variants
Active tracks: None
Tracks available: None

Reading records: 100%|███████████████████████████████████████████████| 511/511 [00:00<00:00, 310982.20 record/s]

✅ chrX → Dataset shape: (511, 2548, 2)

/grid/kinney/home/zhliu/vep_dna/VEP_splicing/testing/src/dataset.py:239: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  self.matching_indices = self.gvl.rows.with_row_count().filter(pl.col("region_idx") == pl.col("site_idx")).get_column("row_nr").to_numpy()